### ISSUE TITLE
Config. Options Dropdown

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/ListDoc-module#1]
The config. options seem to be in a selection box as opposed to the drop-down in the plugin.
Not sure if this intentional, but looks cleaner in dropdown form.

![my evolution site evo cms manager](https://user-images.githubusercontent.com/6113504/34001902-25d1d43a-e0e9-11e7-85a5-76436f712a56.png)

**Comment by Nicola1971** [comment]
yes forgot this difference
 plugins use "list" for config dropdown
module use "menu"
