### ISSUE TITLE
v2.0.5.1 

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/ListDoc-module#2]
Similar to the widget, no dialog messages with the exception of Duplicate.

Delete button no longer works, does not delete resource.

In module config., some options are displaying as dropdown, others as select...
![doclistmodule](https://user-images.githubusercontent.com/6113504/34179064-61519178-e501-11e7-9ea8-24c238bd97e4.png)

**Comment by Nicola1971** [comment]
dialog are fixed. 
Module config issue seems related to an update issue (not updated settings). 
if you use Package Manager, try to rename/delete before update.

**Comment by risingisland** [comment]
Same as stated in widget.

Config. displays correctly now.
