### ISSUE TITLE
Issues with Evo1.4.x

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/ListDoc-module#4]
Hello Nicola,
Not sure if you are still supporting this or not, but I just added it to Evo 1.4.11 and found a few issues:

- Search bar is behind display items per page. May needs a float: right?
- Search icon not displaying.
- ~~Random trash icon showing up?~~  just realized that an empty trash

![CMS Admin ](https://user-images.githubusercontent.com/6113504/83943752-5babca80-a7f6-11ea-9b20-efda7b55e50c.png)

**Comment by Nicola1971** [comment]
seems ok in 2.0.5.6 - Evolution CE 1.4.20
